### PR TITLE
Add check-repositories workflow

### PR DESCRIPTION
**Pull request by 0xLucca**
Add a new workflow that automates the process of checking for outdated repositories and creating GitHub issues to track them

### CODE REVIEW

**Comment by 0xLucca** [comment]
We should decide how to keep track of the repositories and their version tags. In this scripts, I'm assuming we have a JSON file in the repo called `repositories.json` with the following format:
```json
[
  {
    "repository": "https://github.com/AcalaNetwork/chopsticks",
    "tag": "0.13.2"
  },
  {
    "repository": "https://github.com/paritytech/zombienet",
    "tag": "v1.3.105"
  }
]
```

But we could also have a similar structure in the `variables.yaml` file. What do you think? @nhussein11 @albertov19 @eshaben @dawnkelly09

**Comment by 0xLucca** [comment]
> So, I was about to propose to fetch this info from `variables.yaml` directly. Even though the `repository` key might not be used in mkdocs, I believe it makes sense to have both together (repository and tag). We can end up having an structure like the following:
> 
> ```yaml
> dev_tools:
>   chopsticks: 
>     repository: https://github.com/AcalaNetwork/chopsticks
>     version: 0.13.1
>   zombienet:
>     repository: https://github.com/paritytech/zombienet
>     version: 1.3.106
>     architecture: macos-arm64
> ```

Something like this will work. I would only change the parent key, `dev-tools` in this case. When documentation grows, we may have more repositories that may not fit under the dev-tools key, so we will need a more generic one where we can store all the information for each repository we are documenting.

**Comment by eshaben** [comment]
@nhussein11 @0xLucca I definitely agree with having it in the `variables.yml` file. Sounds like you guys have this covered, so I'll leave the specifics to you 🙂

**Review by nhussein11 — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
