### PR TITLE
Paseo Network Feedback: add permalink

### PR DESCRIPTION
**Pull request by eshaben**
This adds a link to the end of all headers

### CODE REVIEW

**Comment by nhussein11** [comment]
Thank you! It works perfectly! 💯

@0xLucca, do you think it's worth merging these changes with the script I built in #9 so users can easily copy the permalink to their clipboards? That would make sharing these links much easier.

**Review by 0xLucca — APPROVED** [review]
Cool! It's a nice feature. Works as expected

**Comment by 0xLucca** [comment]
@nhussein11 I think Erin's solution fixes the issue more idiomatically without having to use custom js. I would merge this and remove the script

**Comment by nhussein11** [comment]
@0xLucca yes, agree on that. However, this solution does not copy the route to your clipboard so you can share it...

That's why I thought about merging these changes with a JS script to add that functionality

**Pull request merged**
