### PR TITLE
Add CI to deploy website to GitHub pages

### PR DESCRIPTION
**Pull request by 0xLucca**

### CODE REVIEW

**Comment by albertov19** [comment]
Great! Let's wait until we have a landing page (cc @eshaben @dawnkelly09 )

**Review by eshaben — APPROVED** [review]
LGTM

**Comment by albertov19** [comment]
> @0xLucca @albertov19 all good to move forward this now

@0xLucca do we want to try the scaffold template

**Comment by 0xLucca** [comment]
I'll try with the template from their docs

**Comment by 0xLucca** [comment]
I tried using their template, and it failed, probably because we have more markdown extensions than the default mkdocs material setup. Let's stick with the CI that works in the demo-docs for now

**Pull request merged**
